name: Exercise1
version: 0.0.1
description: A sample command-line application

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  csv: ^5.0.2
  test: ^1.24.2

dev_dependencies:
#  unittest: any

assets:
   - test_files/
